In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/AAPL.csv")
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,1980-12-12,0.128348,0.128906,0.128348,0.128348,0.100323,469033600
1,1980-12-15,0.122210,0.122210,0.121652,0.121652,0.095089,175884800
2,1980-12-16,0.113281,0.113281,0.112723,0.112723,0.088110,105728000
3,1980-12-17,0.115513,0.116071,0.115513,0.115513,0.090291,86441600
4,1980-12-18,0.118862,0.119420,0.118862,0.118862,0.092908,73449600
...,...,...,...,...,...,...,...
10404,2022-03-18,160.509995,164.479996,159.759995,163.979996,163.979996,123351200
10405,2022-03-21,163.509995,166.350006,163.009995,165.380005,165.380005,95811400
10406,2022-03-22,165.509995,169.419998,164.910004,168.820007,168.820007,81532000
10407,2022-03-23,167.990005,172.639999,167.649994,170.210007,170.210007,98062700
10408,2022-03-24,171.059998,174.139999,170.210007,174.070007,174.070007,90018700

In [3]:
print(df.head())

         Date      Open      High       Low     Close  Adj Close     Volume
0  1980-12-12  0.128348  0.128906  0.128348  0.128348   0.100323  469033600
1  1980-12-15  0.122210  0.122210  0.121652  0.121652   0.095089  175884800
2  1980-12-16  0.113281  0.113281  0.112723  0.112723   0.088110  105728000
3  1980-12-17  0.115513  0.116071  0.115513  0.115513   0.090291   86441600
4  1980-12-18  0.118862  0.119420  0.118862  0.118862   0.092908   73449600

In [4]:
print(df.shape)

(10409, 7)

In [5]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10409 entries, 0 to 10408
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       10409 non-null  object
 1   Open       10409 non-null  float64
 2   High       10409 non-null  float64
 3   Low        10409 non-null  float64
 4   Close      10409 non-null  float64
 5   Adj Close  10409 non-null  float64
 6   Volume     10409 non-null  int64
dtypes: float64(5), int64(1), object(1)
memory usage: 569.4+ KB
None

In [6]:
print(df.describe())

               Open          High           Low         Close     Adj Close  \
count  10409.000000  10409.000000  10409.000000  10409.000000  10409.000000
mean      13.959910     14.111936     13.809163     13.966757     13.350337
std       30.169244     30.514878     29.835055     30.191696     29.911132
min        0.049665      0.049665      0.049107      0.049107      0.038384
25%        0.281964      0.287946      0.274554      0.281250      0.234799
50%        0.468750      0.477679      0.459821      0.468750      0.386853
75%       14.217857     14.364286     14.043571     14.206071     12.188149
max      182.630005    182.940002    179.119995    182.009995    181.778397

             Volume
count  1.040900e+04
mean   3.321778e+08
std    3.393344e+08
min    0.000000e+00
25%    1.247604e+08
50%    2.199680e+08
75%    4.126108e+08
max    7.421641e+09

In [7]:
df["Date"] = pd.to_datetime(df["Date"], utc=True)
df['Date'].dtype

datetime64[ns, UTC]

In [8]:
print(df.isnull().sum())

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [9]:
highest_price_record = df['Adj Close'].max()
display(highest_price_record)

181.778397

In [10]:
lowest_price_record = df['Adj Close'].min()
display(lowest_price_record)

0.038384

In [11]:
average_open_price = df['Open'].mean()
average_close_price = df['Close'].mean()

print(f"Average Opening Price: {average_open_price:.2f}")
print(f"Average Closing Price: {average_close_price:.2f}")

Average Opening Price: 13.96
Average Closing Price: 13.97

In [12]:
df = df.sort_values("Date")
df["Daily_Delta"] = df["Close"] - df["Open"]
df

,Date,Open,High,Low,Close,Adj Close,Volume,Daily_Delta
0,1980-12-12 00:00:00+00:00,0.128348,0.128906,0.128348,0.128348,0.100323,469033600,0.000000
1,1980-12-15 00:00:00+00:00,0.122210,0.122210,0.121652,0.121652,0.095089,175884800,-0.000558
2,1980-12-16 00:00:00+00:00,0.113281,0.113281,0.112723,0.112723,0.088110,105728000,-0.000558
3,1980-12-17 00:00:00+00:00,0.115513,0.116071,0.115513,0.115513,0.090291,86441600,0.000000
4,1980-12-18 00:00:00+00:00,0.118862,0.119420,0.118862,0.118862,0.092908,73449600,0.000000
...,...,...,...,...,...,...,...,...
10404,2022-03-18 00:00:00+00:00,160.509995,164.479996,159.759995,163.979996,163.979996,123351200,3.470001
10405,2022-03-21 00:00:00+00:00,163.509995,166.350006,163.009995,165.380005,165.380005,95811400,1.870010
10406,2022-03-22 00:00:00+00:00,165.509995,169.419998,164.910004,168.820007,168.820007,81532000,3.310012
10407,2022-03-23 00:00:00+00:00,167.990005,172.639999,167.649994,170.210007,170.210007,98062700,2.220002
10408,2022-03-24 00:00:00+00:00,171.059998,174.139999,170.210007,174.070007,174.070007,90018700,3.010009

In [13]:
# Sort descending by Daily_Delta, take the top 10
top10_gains = df.sort_values("Daily_Delta", ascending=False).head(10)
display(top10_gains)

,Date,Open,High,Low,Close,Adj Close,Volume,Daily_Delta
10388,2022-02-24 00:00:00+00:00,152.580002,162.850006,152.000000,162.740005,162.740005,141147500,10.160003
10028,2020-09-21 00:00:00+00:00,104.540001,110.190002,103.099998,110.080002,109.078148,195713800,5.540001
10329,2021-11-30 00:00:00+00:00,159.990005,165.520004,159.919998,165.300003,165.089676,174048100,5.309998
10008,2020-08-21 00:00:00+00:00,119.262497,124.867500,119.250000,124.370003,123.238098,338054800,5.107506
10331,2021-12-02 00:00:00+00:00,158.740005,164.199997,157.800003,163.759995,163.551620,136739200,5.019990
10370,2022-01-28 00:00:00+00:00,165.710007,170.350006,162.800003,170.330002,170.113266,179935700,4.619995
10371,2022-01-31 00:00:00+00:00,170.160004,175.000000,169.509995,174.779999,174.557602,115541600,4.619995
10043,2020-10-12 00:00:00+00:00,120.059998,125.180000,119.279999,124.400002,123.267815,240226800,4.340004
10337,2021-12-10 00:00:00+00:00,175.210007,179.630005,174.690002,179.449997,179.221664,115402700,4.239990
10401,2022-03-15 00:00:00+00:00,150.899994,155.570007,150.380005,155.089996,155.089996,92964300,4.190002

In [14]:
df["Daily_Return"] = ((df["Close"] - df["Open"]) / df["Open"]) * 100
df

,Date,Open,High,Low,Close,Adj Close,Volume,Daily_Delta,Daily_Return
0,1980-12-12 00:00:00+00:00,0.128348,0.128906,0.128348,0.128348,0.100323,469033600,0.000000,0.000000
1,1980-12-15 00:00:00+00:00,0.122210,0.122210,0.121652,0.121652,0.095089,175884800,-0.000558,-0.456591
2,1980-12-16 00:00:00+00:00,0.113281,0.113281,0.112723,0.112723,0.088110,105728000,-0.000558,-0.492580
3,1980-12-17 00:00:00+00:00,0.115513,0.116071,0.115513,0.115513,0.090291,86441600,0.000000,0.000000
4,1980-12-18 00:00:00+00:00,0.118862,0.119420,0.118862,0.118862,0.092908,73449600,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...
10404,2022-03-18 00:00:00+00:00,160.509995,164.479996,159.759995,163.979996,163.979996,123351200,3.470001,2.161860
10405,2022-03-21 00:00:00+00:00,163.509995,166.350006,163.009995,165.380005,165.380005,95811400,1.870010,1.143667
10406,2022-03-22 00:00:00+00:00,165.509995,169.419998,164.910004,168.820007,168.820007,81532000,3.310012,1.999886
10407,2022-03-23 00:00:00+00:00,167.990005,172.639999,167.649994,170.210007,170.210007,98062700,2.220002,1.321508
10408,2022-03-24 00:00:00+00:00,171.059998,174.139999,170.210007,174.070007,174.070007,90018700,3.010009,1.759622

In [15]:
# Sort descending by Daily_Return, take the top 10 loesses
top10_losses = df.sort_values("Daily_Return", ascending=True).head(10)
display(top10_losses)

,Date,Open,High,Low,Close,Adj Close,Volume,Daily_Delta,Daily_Return
1731,1987-10-19 00:00:00+00:00,0.430804,0.430804,0.316964,0.325893,0.255451,476000000,-0.104911,-24.352374
1736,1987-10-26 00:00:00+00:00,0.308036,0.312500,0.246652,0.250000,0.195962,313600000,-0.058036,-18.840655
7013,2008-09-29 00:00:00+00:00,4.272143,4.274286,3.592500,3.759286,3.218980,2622057200,-0.512857,-12.004678
691,1983-09-07 00:00:00+00:00,0.175223,0.175223,0.151228,0.154576,0.120824,384854400,-0.020647,-11.783270
7019,2008-10-07 00:00:00+00:00,3.588571,3.625000,3.176786,3.184286,2.726622,1878772000,-0.404285,-11.265905
4276,1997-11-10 00:00:00+00:00,0.187500,0.191964,0.165179,0.166853,0.142872,1398241600,-0.020647,-11.011733
4746,1999-09-23 00:00:00+00:00,0.635045,0.636161,0.562500,0.565290,0.484043,1143755200,-0.069755,-10.984261
5006,2000-10-03 00:00:00+00:00,0.445313,0.446429,0.396205,0.398438,0.341172,2038120000,-0.046875,-10.526304
4819,2000-01-06 00:00:00+00:00,0.947545,0.955357,0.848214,0.848214,0.726304,767972800,-0.099331,-10.482985
7024,2008-10-14 00:00:00+00:00,4.152143,4.157143,3.683571,3.717143,3.182894,1980994400,-0.435000,-10.476518

In [16]:
average_volume = df["Volume"].mean()
maximum_volume = df["Volume"].max()
minimum_volume = df["Volume"].min()

print("Average Volume:", average_volume)
print("Maximum Volume:", maximum_volume)
print("Minimum Volume:", minimum_volume)

Average Volume: 332177847.17071766
Maximum Volume: 7421640800
Minimum Volume: 0

In [20]:
threshold = 2 * average_volume
anomalous_days = df[df["Volume"] > threshold]
print("\nAnomalous Trading Days:\n")
print(anomalous_days[["Date", "Open", "Close", "Daily_Delta", "Daily_Return", "Volume"]])

Anomalous Trading Days:

                          Date       Open      Close  Daily_Delta  \
532  1983-01-20 00:00:00+00:00   0.150112   0.166853     0.016741
703  1983-09-23 00:00:00+00:00   0.111607   0.108259    -0.003348
704  1983-09-26 00:00:00+00:00   0.108817   0.111049     0.002232
735  1983-11-08 00:00:00+00:00   0.087054   0.079799    -0.007255
1070 1985-03-07 00:00:00+00:00   0.109933   0.098772    -0.011161
...                        ...        ...        ...          ...
8354 2014-01-28 00:00:00+00:00  18.170000  18.089287    -0.080713
8356 2014-01-30 00:00:00+00:00  17.947857  17.849285    -0.098572
8414 2014-04-24 00:00:00+00:00  20.293215  20.277500    -0.015715
8416 2014-04-28 00:00:00+00:00  20.457144  21.217501     0.760357
8509 2014-09-09 00:00:00+00:00  24.770000  24.497499    -0.272501

      Daily_Return      Volume
532      11.152340   707840000
703      -2.999812  2832345600
704       2.051150   768768000
735      -8.333908  1221516800
1070    -10.152547   733980800
...            ...         ...
8354     -0.444210  1065523200
8356     -0.549213   678501600
8414     -0.077440   759911600
8416      3.716829   669485600
8509     -1.100125   759385200

[1265 rows x 6 columns]

In [23]:
mean_return = df["Daily_Return"].mean()
print(f"Mean: {mean_return}")

variance_return = df["Daily_Return"].var()
print(f"Variance: {variance_return}")

std_return = df["Daily_Return"].std()
print(f"Standard Deviation: {std_return}")

Mean: -0.007888465889642643
Variance: 5.386275413328653
Standard Deviation: 2.3208350681012755